name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

    
jobs:
  build:
    name: hwloc build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: open-mpi/hwloc.git
          ref: v2.12 # use version 2.12 of HWLOC
      - uses: actions/cache@v4
        id: cache-hwloc
        with:
          path: ~/hwloc-install
          key: hwloc-${{ runner.os }}-v2.12
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
      - run: |
          mkdir build 
          ./autogen.sh
          cd build
          ../configure --prefix=$HOME/hwloc-install
          make -j$(nproc)
          make install
