name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-stack:
    # ----------- hwloc -------------
    name: hwloc build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: open-mpi/hwloc.git
          ref: v2.12 # use version 2.12 of HWLOC
      - name: Cache hwloc
        uses: actions/cache@v4
        id: cache-hwloc
        with:
          path: ~/hwloc-install
          key: hwloc-${{ runner.os }}-v2.12
          
      - name: Build hwloc
        if: steps.cache-hwloc.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
          mkdir build 
          ./autogen.sh
          cd build
          ../configure --prefix=$HOME/hwloc-install
          make -j$(nproc)
          make install
      - name: Add to PATH
        run: echo "$HOME/hwloc-install/bin" >> $GITHUB_PATH
        
      # ---------- libevent ------------
      - name: Cache libevent
        uses: actions/cache@v4
        id: cache-libevent
        with:
          path: ~/libevent-install
          key: libevent-${{ runner.os }}-v2.1.12
      - name: Build hwloc
        if: steps.cache-libevent.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
          tar -xzf libevent-2.1.12-stable.tar.gz
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
          cd libevent-2.1.12-stable
          ./configure --prefix=$HOME/libevent-install --disable-shared --enable-static --with-pic
          make -j$(nproc)
          make install -j$(nproc)
      - name: Add to PATH
        run: echo "$HOME/libevent-install/bin" >> $GITHUB_PATH

      # ---------- pmix -------------
      - name: Cache pmix
        uses: actions/cache@v4
        id: cache-pmix
        with:
          path: ~/pmix-install
          key: pmix-${{ runner.os }}-v5.0.2
      - name: Build pmix
        if: steps.cache-pmix.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/openpmix/openpmix/releases/download/v5.0.2/pmix-5.0.2.tar.bz2
          tar -xjf pmix-5.0.2.tar.bz2          
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
          cd pmix-5.0.2
          mkdir build; cd build
          ../configure --prefix=$HOME/pmix-install --with-libevent=$HOME/libevent-install/ --with-hwloc=$HOME/hwloc-install/
          make -j$(nproc)
          make install -j$(nproc)
      - name: Add to PATH
        run: echo "$HOME/pmix-install/bin" >> $GITHUB_PATH
        
      # ------------  ucx ----------------
      - uses: actions/checkout@v5
        with:
          repository: openucx/ucx.git
          ref: v1.19.x # use version `1.19.x of ucx
      - name: Cache ucx
        uses: actions/cache@v4
        id: cache-ucx
        with:
          path: ~/ucx-install
          key: ucx-${{ runner.os }}-v1.19.x
      - name: Build ucx
        if: steps.cache-ucx.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
          cd ucx
          git submodule update --init --recursive
          mkdir build 
          ./autogen.sh
          export CC=`which gcc`
          export CXX=`which g++`
          ./contrib/configure-release \
            CFLAGS="-Wno-error=unused-but-set-variable" \
            CXXFLAGS="-Wno-error=unused-but-set-variable" \
            --prefix=$UCX_DIR \
            --with-rc \
            --with-with-ud \
            --with-dc \
            --with-mlx5-dv \
            --enable-mt
          make -j$(nproc)
          make install -j$(nproc)
      - name: Add to PATH
        run: echo "$HOME/ucx-install/bin" >> $GITHUB_PATH
        
      # -------------- ompi ---------------
      - name: Cache ompi
        uses: actions/cache@v4
        id: cache-ompi
        with:
          path: ~/ompi-install
          key: ompi-${{ runner.os }}-v5.0.4
      - name: Build ompi
        if: steps.cache-ompi.outputs.cache-hit != 'true'
        run: |
          wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.4.tar.gz
          tar -xzf openmpi-5.0.4.tar.gz          
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
          mkdir build; cd build
          cd openmpi-5.0.4
          ./configure \
           --prefix=$HOME/ompi-install/ \
           --disable-static \
           --disable-silent-rules \
           --enable-shared \
           --with-ucx=$HOME/ucx-install/ \
           --without-hcoll \
           --without-xpmem \
           --without-ofi \
           --without-psm \
           --without-mxm \
           --without-knem \
           --without-psm2 \
          --without-ucc \
          --without-cma \ 
          --without-fca \
          --without-cray-xpmem \
          --without-alps \
          --without-lsf \
          --without-sge \
          --without-loadleveler \
          --disable-memchecker \
          --with-libevent=$HOME/libevent-install/ \
          --with-pmix=$HOME/pmix-install/ \
          --with-hwloc=$HOME/hwloc-install \
          --disable-java \
          --disable-mpi-java \
          --disable-io-romio \
          --with-gpfs=no \
          --without-cuda \
          --enable-oshmem \
          --enable-wrapper-rpath \
          --disable-wrapper-runpath \
          CFLAGS=-DYY_BUF_SIZE=1048576 \
          --disable-debug
          make install -j$(nproc)
      - name: Add to PATH
        run: echo "$HOME/libevent-install/bin" >> $GITHUB_PATH
        
      # ------------- osss-ucx  ---------------
      - uses: actions/checkout@v5
        with:
          repository: GraysenGould/osss-ucx.git
          ref: main # use main branch (version 1.5)
      - name: Cache osss-ucx
        uses: actions/cache@v4
        id: cache-osss-ucx
        with:
          path: ~/osss-ucx-install
          key: osss-ucx-${{ runner.os }}-v1.5
      - name: Build osss-ucx
        if: steps.cache-osss-ucx.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
          cd osss-ucx
          mkdir build
          ./autogen.sh
          cd build
          export SHMEM_LAUNCHER="$HOME/ompi-install/bin/mpiexec"
          export CC=`which gcc`
          ./configure \
           --prefix=$HOME/osss-ucx-install \
           --with-ucx=$HOME/ucx-install/ \
           --with-pmix=$HOME/pmix-install/ \
           --with-heap-size=128M   \
           --enable-debug=yes
          make install -j$(nproc)
      - name: Add to PATH
        run: echo "$HOME/osss-ucx-install/bin" >> $GITHUB_PATH
    
