name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

    
jobs:
  build:
    name: hwloc build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: open-mpi/hwloc.git
          ref: v2.12 # use version 2.12 of HWLOC
      - run: cd hwloc
      - run: mkdir build
      - run: ./autogen.sh
      - run: cd build
      - run: ../configure
      - run: make
      - run: make install
