name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: hwloc build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: open-mpi/hwloc.git
          ref: v2.12 # use version 2.12 of HWLOC
      - name: Cache hwloc
        uses: actions/cache@v4
        id: cache-hwloc
        with:
          path: ~/hwloc-install
          key: hwloc-${{ runner.os }}-v2.12
          
      - name: Build hwloc
        if: steps.cache-hwloc.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          build-essential
          mkdir build 
          ./autogen.sh
          cd build
          ../configure --prefix=$HOME/hwloc-install
          make -j$(nproc)
          make install
      - name: Add to PATH
        run: echo "$HOME/hwloc-install/bin" >> $GITHUB_PATH
